from dataclasses import dataclass


@dataclass(frozen=True)
class CombinedBaselineConfig:
    num_epochs: int = 10
    batch_size: int = 4
    seed: int = 42
    target_size: int = 448
    pred_threshold: float = 0.5
    harden_temperature: float = 0.7
    hard_clip_low: float = 0.1
    hard_clip_high: float = 0.9
    min_component_area: int = 50
    train_subset: int | None = None
    val_subset: int | None = None
    lr: float = 1e-4
    grad_clip_max_norm: float = 1.0
    train_num_workers: int = 2
    val_num_workers: int = 1
    dino_mean: tuple[float, float, float] = (0.485, 0.456, 0.406)
    dino_std: tuple[float, float, float] = (0.229, 0.224, 0.225)
    dino_model_name: str = "dinov2_vitb14"
    dino_embed_dim: int = 768
    freeze_dino_encoder: bool = True
    use_amp: bool = True
    data_root: str = "data"
    train_ratio: float = 0.8
    val_ratio: float = 0.1
    test_ratio: float = 0.1
    compute_pixel_f1: bool = False
    verify_score_equivalence: bool = False
    validation_inference_mode: str = "direct"
    validation_probability_dtype: str = "float16"
    validation_log_timing: bool = True
    post_process_confident_threshold: float | None = None
    post_process_smooth_probabilities: bool = False
    post_process_fill_holes: bool = True
    post_process_apply_opening: bool = True
    post_process_apply_closing: bool = False
    post_process_keep_confident_seeded_components: bool = False
    run_dir: str = "runs/combined_baseline"
    latest_checkpoint_name: str = "latest.pt"
    best_checkpoint_name: str = "best_by_kaggle_score.pt"
    resume: bool = True
    save_predictions: bool = False
    patchmatch_loss_weight: float = 0.8
    separate_transforms: bool = True
    cnn_feature_norm: bool = True
    pm_iters: int = 24
    pm_beta: float = 10.0
    pm_hard_selection: bool = True
    pm_random_window: int = 50
    pm_use_non_local: bool = True
    pm_non_local_limit: float = 25.0
    pm_flat_threshold: float = 0.15
    pm_margin_threshold: float = 0.10
    pm_topk: int = 1
    pm_reduced_precision: bool = True
    dlf_error_scaling: str = "log1p"
